### ISSUE TITLE
The plugin-localized overwrite the root getData properties

### ISSUE THREAD

**Issue by sti-web** [richardwohlgemuth/react-static-plugin-localized#24]
Hi, I tried to use your plugin but got an issue.
The issue is my variables from ./static.config.js file are overwritten by the plugin, and I can't fetch them in any component.
For ex. Blog page - src/pages/blog.js
`const { posts, locale, location } = useRouteData();`
http://localhost:3000/blog - variables locale and location aren't available, variable posts comes from original ./static.config.js file
http://localhost:3000/en/blog - variable posts is overwritten and I got posts from 'data/custom/en.json' file

If you need any clarification, please contact me. Thanks

**Comment by sti-web** [comment]
The crutch fix will be like this.
Fetch the data, and synchronously write to dedicated language file, then the plugin will read the data from a file.

**Comment by woffrek** [comment]
Hi sti-web,
could you provide the static.config.js?
Maybe another react-static-plugin overrides the data before it is accessed by your component.

**Comment by sti-web** [comment]
Hi @woffrek,
sorry for late response.
This is my static.config.js file:
`import path from "path";
import axios from "axios";
import buildConfig from "./build.config";

process.env.REACT_STATIC_SITE_VERSION = "1.3.x";

const ts = Date.now();

export default {
  silent: true,
  extractCssChunks: false, // enables automatic CSS splitting into separate files 
  maxThreads: 8,
  getRoutes: async() => {

    process.env.REACT_STATIC_SERVER_API =
      process.env.NODE_ENV === "development" ?
      "http://localhost:3030" :
      "https://real-web-page.com/api";

    process.env.REACT_STATIC_SERVER_PROTOCOL =
      process.env.NODE_ENV === "development" ? "http" : "https";

    process.env.REACT_STATIC_LOCALHOST =
      process.env.NODE_ENV === "development" ?
      "http://localhost:3030" :
      "https://real-web-page.com/api";

    const { data: instructors } = await axios.get(
      `${process.env.REACT_STATIC_LOCALHOST}/instructors?ts=${ts}`
    );

    const { data: lessons } = await axios.get(
      `${process.env.REACT_STATIC_LOCALHOST}/lessons?ts=${ts}`
    );

    const { data: courses } = await axios.get(
      `${process.env.REACT_STATIC_LOCALHOST}/courses?ts=${ts}`
    );

    return [
      { path: "/" },
      { path: "/404" },
      { path: "/signin" },
      { path: "/contacts" },
      { path: "/general-conditions" },
      { path: "/thank-you" },
      { path: "/register" },
      { path: "/forgot-password" },
      { path: "/reset-password" },
      { path: "/cancel-subs" },
      { path: "/my-account" },
      { path: "/my-lessons" },
      { path: "/my-skills" },
      { path: "/my-skills-add" },
      { path: "/my-history" },
      { path: "/my-activity" },
      { path: "/subscription" },
      { path: "/kupyty-zaraz" },
      {
        path: "/instructors",
        children: instructors.map((instructor) => ({
          path: `/${instructor.slug}`,
          template: "src/containers/Instructor",
        })),
      },
      {
        path: "/explore",
        children: lessons.map((lesson) => ({
          path: `/${lesson.slug}`,
          template: "src/containers/Lesson",
        })),
      },
      {
        path: "/course",
        children: courses.filter(course => course.type === 'course').map((course) => ({
          path: `/${course.slug}`,
          template: "src/containers/Course",
        })),
      },
      {
        path: "/playlist",
        children: courses.filter(course => course.type === 'playlist').map((course) => ({
          path: `/${course.slug}`,
          template: "src/containers/Course",
        })),
      },
    ];
  },
  plugins: [
    [
      require.resolve("react-static-plugin-source-filesystem"),
      {
        location: path.resolve("./src/pages"),
      },
    ],
    [
      require.resolve("react-static-plugin-localized"),
      {
        config: buildConfig,
      },
    ],
    require.resolve("react-static-plugin-sitemap"),
  ],
};
`
